# Day One :)

## Intro to Econ

 ***MICROECONOMICS***

- Analyzes choices made by individual participants within an economy.
- Tries to figure out the reasons people make certain financial decisions.
  - Deciding wages/purchasing choices.

***MACROECONOMICS***

- Analyzes the overall performance of an economy.
  - Total production, price level, rate of inflation, employment, unemployment, rate of growth.


**Scarcity**: The imbalance between our desires and the means of satisfying those desires

**Opportunity Cost**: The sacrifice of the next best alternative use of resources then those resources are used for any specific purpose. 


### Marginal Analysis
- Means *extra*
- [Marginal benefit](https://www.investopedia.com/terms/m/marginalbenefit.asp)
: Is the value place on an extra (one more) unit of an item
- [Marginal cost](http://economicsconcepts.com/marginal_cost.htm)
: Is the value of the sacrifice made to obtain an additional unit of an item.

### Rational Behavior
- Occurs when individuals seek net gains by undertaking actions for which marginal benefit (MB) exceeds marginal cost (MC)
- When marginal benefit exceeds marginal cost of an activity a rational person will undertake more of that activity.
